insert into solution values (1, "Banking - Transaction Banking");
insert into solution values (2, "Banking - Embedded Consumer Finance");
insert into solution values (3, "Analytics - ProTool Pro");
insert into solution values (4, "Analytics - Portfolio Analytics");
insert into solution values (5, "Analytics - GS Quant");
insert into solution values (6, "Data - Curated Data");
insert into solution values (7, "Data - Data Management");
insert into solution values (8, "Data - Data Analytics");

insert into feature values (1, 1, "Create & Manage Virtual Accounts", "Create and modify virtual accounts, which act as subledgers underneath an existing (virtual-enabled) commercial deposit account.");
insert into feature values (1, 2, "Originate Paymenets", "Originate payments and collections equests on-demand via US Fedwire, US ACH, and SWIFT. After initiating a payment request, our payment status APIs allow Clients to track the progrss of payment before debiting or crediting their  accounts.");
insert into feature values (1, 3, "Track Account Activity", "Track real-time ledger activities, which keep track of payments that are in a terminal state (E.g. have been settled)");
insert into feature values (1, 4, "Review Incoming Payments", "End users receive notifications when a third part attempt to debit or credit their accounts. They may subsequently approve or reject theese incoming payments, based on their preferences and policies.");
insert into feature values (1, 5, "Forex Payments", "Provides spot transaction rates in Real Time, allowing users to make payments using a currency of their choice or make bulk purchases of Foreign Currency.");
insert into feature values (2, 6, "Investment Automation", "Access to digitally managed investment portfolios.");
insert into feature values (2, 7, "Personalised Insights", "Intuitive tools & trackers with personalised insights.");
insert into feature values (2, 8, "Loans", "Provide quotations to users for line of credit at competitive rates from Goldman Sachs.");
insert into feature values (2, 9, "High Yield Savings Products, CDs", "Offer Goldman Sachs' award-winning consumer financial products within your digital retail experiences."); 
insert into feature values (3, 10, "Analyze Data", "Analyze data using rich library of mathematical functions including algebraic, econometric and technical functions.");       
insert into feature values (3, 11, "Access Rich Data", "Access rich data that provides you with extra information to make your business decisions.");
insert into feature values (3, 12, "Backtest Strategies", "You can run backtests on the fly that is integrated and understand your factor exposures and analysis.");
insert into feature values (3, 13, "Access to Historical Data across Major Markets", "You can access historical data pertaining to your industry to uncover trends.");
insert into feature values (4, 14, "Improve Efficiency in Discovering Sources of Risk and Returns", "Using our integrated data-model, industry-leading analytics, you can improve the efficiency of risk and returns.");
insert into feature values (4, 15, "Curate your Own Data and Analytics", "Put all your portfolio data, curated market data and anayltics together at your fingertips.");
insert into feature values (4, 16, "Securely Integrate and Connect Third Party Data", "Securely integrate or connect to third-party factor risk data to gain operational efficiencies to turn insights to action.");
insert into feature values (5, 17, "Toolkit for Quantitative Finances", "This toolkit is created by Quantts to manage the global trading business.");
insert into feature values (5, 18, "Accelerate Development of Trading Strategies and Risk Management Solutions", "This toolkit is designed to accelerate development strategies and risk management solutions.");
insert into feature values (6, 19, "Access Third Party Data", "Utilising AWS Data Exchange, you may find, subscribe to, and use data in the cloud, as well as a selection of GS-curated third party data. Interact with market data via tools such as our probability and risk analysis model.");
insert into feature values (7, 20, "Easily Set Up Your Own Data Management System", "Removes the burden of building your own data management system because you can use Goldman Sachs's managed tick database.");
insert into feature values (7, 21, "Horizontally Scalable", "Easily add new infrasturcture via the cloud to cope with new demands.");
insert into feature values (7, 22, "Standardise Data", "Unifying framework to map data into a consistent data model.");
insert into feature values (8, 23, "Data Analysis", "Rapidly turn data into actionable insights.");
insert into feature values (8, 24, "Backtesting of Complex Trading Strategies", "Historical data and GS powerful analytical tools allow backtesting of complex strategies.");    
insert into feature values (8, 25, "Data Visualisation", "Provide easy visualisation of data, made scalable through cloud computing.");
insert into feature values (8, 26, "Time Series Analytics", "Provide powerful time series analytics to comprehend complex market dynamics .");